# -*- coding: utf-8 -*-
"""
/***************************************************************************
 projectFTS
                                 A QGIS plugin
 This plugin generates a full text search index containing all attributes of all layers of a loaded project. The user then can use a single text-input field to search within all available attributes.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-07-14
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Markus Mayr
        email                : markus.mayr@gisforge.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.core import QgsMessageLog
from qgis.core import QgsProject
import sqlite3

def init_db():
    QgsMessageLog.logMessage(f"QgsProject.fileName(): {QgsProject.fileName()}", tag="ftsPlugin", level=QgsMessageLog.INFO)
    QgsMessageLog.logMessage(f"QgsProject.fileInfo(): {QgsProject.fileName()}", tag="ftsPlugin", level=QgsMessageLog.INFO)
    pass